# -*- coding: utf-8 -*-
"""ILPD_knn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pe8kI8GYqhq-iFGd6cag4nSP1B8NxbJ5
"""

import pandas as pd
import re
import numpy as np
import itertools
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv("/content/drive/MyDrive/Indian Liver Patient Dataset (ILPD).csv", header=None)

df.columns = [
    'Age',
    'Gender',
    'Total_Bilirubin',
    'Direct_Bilirubin',
    'Alkaline_Phosphotase',
    'Alamine_Aminotransferase',
    'Aspartate_Aminotransferase',
    'Total_Proteins',
    'Albumin',
    'Albumin_and_Globulin_Ratio',
    'Target'
]

df

df.head()

df.shape

df.dtypes

df.info()

df.describe()

# Melihat Nilai Kosong
df.isnull().sum()

# print(df.isnull().sum())

df.isnull()

df.duplicated().sum()

df=df.drop_duplicates()

df.duplicated().sum()

# print(df['Gender'].unique())

# df.loc[:, 'Gender'] = df['Gender'].map({
#     'Female': 0,
#     'Male': 1
# })

# print(df['Gender'].value_counts())

from sklearn.preprocessing import LabelEncoder

# Ubah kolom gender: Female -> 0, Male -> 1
df['Gender'] = df['Gender'].map({'Female': 0, 'Male': 1})

df['Target'] = df['Target'].map({
    1: 1,
    2: 0
})

print(df['Target'])

# from sklearn.preprocessing import LabelEncoder

# le = LabelEncoder()

# df['Target'] = le.fit_transform(df['Target'])

# print(df['Target'].value_counts())

df.info()

from google.colab import drive
drive.mount('/content/drive')

df.head()

df

import warnings
warnings.filterwarnings('ignore')

sns.countplot(data=df)

# df.hist(bins=10,figsize=(10,10))
# plt.show()

#Box Plot
plt.figure(figsize=(16,12))
sns.set_style(style='whitegrid')
plt.subplot(4,3,1)
sns.boxplot(x='Age',data=df)
plt.subplot(4,3,2)
sns.boxplot(x='Gender',data=df)
plt.subplot(4,3,3)
sns.boxplot(x='Total_Bilirubin',data=df)
plt.subplot(4,3,4)
sns.boxplot(x='Direct_Bilirubin',data=df)
plt.subplot(4,3,5)
sns.boxplot(x='Alkaline_Phosphotase',data=df)
plt.subplot(4,3,6)
sns.boxplot(x='Alamine_Aminotransferase',data=df)
plt.subplot(4,3,7)
sns.boxplot(x='Aspartate_Aminotransferase',data=df)
plt.subplot(4,3,8)
sns.boxplot(x='Total_Proteins',data=df)
plt.subplot(4,3,9)
sns.boxplot(x='Albumin',data=df)
plt.subplot(4,3,10)
sns.boxplot(x='Albumin_and_Globulin_Ratio',data=df)
plt.subplot(4,3,11)
sns.boxplot(x='Target',data=df)

# empty_string_rows = df[df['Albumin_and_Globulin_Ratio'] == '']
# print(empty_string_rows)

#jika 1 kolom
df['Albumin_and_Globulin_Ratio'] = df['Albumin_and_Globulin_Ratio'].fillna(df['Albumin_and_Globulin_Ratio'].mean())

# print(df['Albumin_and_Globulin_Ratio'])

df.isnull().sum()

df.describe()

# hitung korelasi
corrmat = df.corr()

# tampilkan heatmap
plt.figure(figsize=(12, 7))
sns.heatmap(corrmat, annot=True)
plt.show()

df_selected=df.drop(['Age','Gender','Alkaline_Phosphotase','Albumin_and_Globulin_Ratio'],axis='columns')

from sklearn.preprocessing import QuantileTransformer
x=df_selected
quantile  = QuantileTransformer()
X = quantile.fit_transform(x)
df_new=quantile.transform(X)
df_new=pd.DataFrame(X)
df_new.columns =['Total_Bilirubin', 'Direct_Bilirubin','Alamine_Aminotransferase','Aspartate_Aminotransferase','Total_Proteins','Albumin','Target']
df_new.head()

# from sklearn.preprocessing import QuantileTransformer
# import pandas as pd

# # Pisahkan fitur dan target
# X = df_selected.drop('Target', axis=1)
# y = df_selected['Target']

# # Quantile hanya untuk fitur
# quantile = QuantileTransformer(random_state=42)

# X_quantile = quantile.fit_transform(X)

# X = pd.DataFrame(
#     X_quantile,
#     columns=X.columns
# )

plt.figure(figsize=(16,12))
sns.set_style(style='whitegrid')
plt.subplot(3,3,1)
sns.boxplot(x=df_new['Total_Bilirubin'],data=df_new)
plt.subplot(3,3,2)
sns.boxplot(x=df_new['Direct_Bilirubin'],data=df_new)
plt.subplot(3,3,3)
sns.boxplot(x=df_new['Alamine_Aminotransferase'],data=df_new)
plt.subplot(3,3,4)
sns.boxplot(x=df_new['Aspartate_Aminotransferase'],data=df_new)
plt.subplot(3,3,5)
sns.boxplot(x=df_new['Total_Proteins'],data=df_new)
plt.subplot(3,3,6)
sns.boxplot(x=df_new['Albumin'],data=df_new)

target_name='Target'
y= df_new[target_name] #given predictions - training data
X=df_new.drop(target_name,axis=1) #dropping kolom Outcome & simpan kolom lainnya menjadi X

X.head() # contains only independent features

y.head() #contains dependent feature

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X,y,test_size=0.2,random_state=0) #splitting data in 80% train, 20%test

X_train.shape,y_train.shape

X_test.shape,y_test.shape

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X,y,test_size=0.2,random_state=0) #splitting data in 80% train, 20%test
X_train

y_train

X_test

y_test

#pemodelan/membangun skenario model
#model decision tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.metrics import f1_score, precision_score, recall_score
from sklearn.model_selection import GridSearchCV
dt = DecisionTreeClassifier(random_state=42)

# Create the parameter grid based on the results of random search
params = {
    'max_depth': [5, 10, 20,25],
    'min_samples_leaf': [10, 20, 50, 100,120],
    'criterion': ["gini", "entropy"]
}

grid_search = GridSearchCV(estimator=dt,
                           param_grid=params,
                           cv=4, n_jobs=-1, verbose=1, scoring = "accuracy")

best_model=grid_search.fit(X_train, y_train)

dt_pred=best_model.predict(X_test)

print("Classification Report is:\n",classification_report(y_test,dt_pred))
print("\n F1:\n",f1_score(y_test,dt_pred))
print("\n Precision score is:\n",precision_score(y_test,dt_pred))
print("\n Recall score is:\n",recall_score(y_test,dt_pred))
print("\n Confusion Matrix:\n")
# Confusion Matrix
cm = confusion_matrix(y_test, dt_pred)
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues")
plt.title("Confusion Matrix - XGBoost")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.metrics import f1_score, precision_score, recall_score
from sklearn.model_selection import GridSearchCV

#List Hyperparameters to tune
knn= KNeighborsClassifier()
n_neighbors = list(range(15,25))
p=[1,2]
weights = ['uniform', 'distance']
metric = ['euclidean', 'manhattan', 'minkowski']

#convert to dictionary
hyperparameters = dict(n_neighbors=n_neighbors, p=p,weights=weights,metric=metric)

#Making model
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
grid_search = GridSearchCV(estimator=knn, param_grid=hyperparameters, n_jobs=-1, cv=cv, scoring='f1',error_score=0)

best_model = grid_search.fit(X_train,y_train)

#Best Hyperparameters Value
print('Best leaf_size:', best_model.best_estimator_.get_params()['leaf_size'])
print('Best p:', best_model.best_estimator_.get_params()['p'])
print('Best n_neighbors:', best_model.best_estimator_.get_params()['n_neighbors'])

#Predict testing set
knn_pred = best_model.predict(X_test)

print("Classification Report is:\n",classification_report(y_test,knn_pred))
print("\n F1:\n",f1_score(y_test,knn_pred))
print("\n Precision score is:\n",precision_score(y_test,knn_pred))
print("\n Recall score is:\n",recall_score(y_test,knn_pred))
print("\n Confusion Matrix:\n")
# Confusion Matrix
cm = confusion_matrix(y_test, knn_pred)
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues")
plt.title("Confusion Matrix - XGBoost")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

#menyimpan model mesin learning yang sudah kita buat

import pickle

pickle.dump(knn_pred, open("ilpd_knn_pred.sav", "wb"))